name: Profile Development Stats

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta diariamente a medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente

permissions:
  contents: write
  workflows: read

jobs:
  update-readme:
    name: Update README with development stats
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Profile Stats
      uses: teoxoy/profile-readme-stats@v1.1.0
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Updated development stats"
